### ISSUE TITLE
Under More app the FSO Link has an extra csumb.edu in front of it  and causing it to error out - https://csumb.edu/https://csumb.okta.com/home/californiastateuniversitymontereybay_webtma_1/0oaal583zwRMPYXNy0x7/alnal5cfcsp26MYyn0x7

### ISSUE THREAD

**Issue by kevee** [csumb/csumb-gatsby#155]

**Comment by kevee** [comment]
Fixed, that was a broken redirect.

**Comment by thburns** [comment]
it looks like it is still an issue -

**Comment by kevee** [comment]
@thburns  - Which link is it? The current Facilities Workorder goes to:

https://csumb.okta.com/home/californiastateuniversitymontereybay_webtma_1/0oaal583zwRMPYXNy0x7/alnal5cfcsp26MYyn0x7

**Comment by thburns** [comment]
It is working now. It was under More apps.
