### ISSUE TITLE
Switch edit site to new edit theme

### ISSUE THREAD

**Issue by kevee** [csumb/csumb-gatsby#160]
- [x] When someone clicks "edit page" they get the old kaleidoscope  Recommend the old 404 error page say something like it looks like you are trying to edit a page but you aren't logged in yet. and give them a log in button.
- [x] Remove the site navigation on edit.csumb.edu
- [x] Add the tool that tells them the last time the live site was built and when expected next build will be.
- [ ] Can we get the gear button to always be there and if they aren't logged in it give them the option to log in?
- [x] Under your account for editors can we have a link to edit.csumb.edu called Editing tools or something like that
- [x] Add a sky blue bar at the top behind the text. Change the text to white and add the button style to Log in. You can use the same sky blue that we’re using for the blue gear.

**Comment by kevee** [comment]
Added CORS to https://csumb.edu/_last-build.json

**Comment by kevee** [comment]
@thburns @flontoc does the last publish notifier look good?

https://test.csumb.edu/

**Comment by flontoc** [comment]
Can we say "The university website..."

My first reaction to the sentence was "Okay, what does that mean?" I think
we need to have some smaller text afterwards that states what it means.
Something like "Any changes made after the last published date and time
will show up on the live site upon completion of the next publish date."
Feel free to edit that statement.

*Francine Lontoc */ User Experience Specialist
Web Services
California State University Monterey Bay
831-582-3864
flontoc@csumb.edu

**Comment by kevee** [comment]
Added message in https://github.com/csumb/csumb/commit/cdd3cb904fc58aa6584c18897e28a4724c2c6cbf
