### ISSUE TITLE
Events not showing up on dashboard based on role

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#222]
Here is an example - https://csumb.edu/clc/events/long-night-against-procrastination-2-1

when the employee_staff is selected it doesn't show up on the dashboard for me.

Same reports for students.

But authenticated user works.

**Comment by kevee** [comment]
Typo. https://github.com/csumb/csumb/commit/804e8ca1871c6ef85afc6f123355daf0987683d1 Pushing now.
