### ISSUE TITLE
Broken link - https://csumb.edu/cashnet/pay/RESERVDEP

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#224]
https://csumb.edu/cashnet/pay/RESERVDEP

**Comment by kevee** [comment]
The new link for this is:

https://csumb.edu/cashnet?category=RESERVDEP

I already tracked down all the pages and fixed whatever links I could find.

**Comment by thburns** [comment]
https://csumb.edu/cashnet?category=RESERVDEP is not giving this error.

https://commerce.cashnet.com/cashneti/selfserve/SAONotAuthorized.aspx

@kevee
