### ISSUE TITLE
People block giving undefined links for department

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#225]
https://csumb.edu/advising/advisor-contact-list this page all the people blocks has a link to the undergrad advising program and they are /undefined. 

Also is that really the department name?

**Comment by kevee** [comment]
https://github.com/csumb/csumb/commit/0923b8b890d047751144c3c5835f07be33b38cf5

**Comment by kevee** [comment]
https://github.com/csumb/opie/commit/35e8397255b3b2cdd0cf8050c21d7d5ffa9677a1
