### ISSUE TITLE
Are redirects broken?

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#229]
https://csumb.edu/impaction
https://csumb.edu/csonline

Or did you delete them again?

**Comment by kevee** [comment]
I purged redirects with less than 100 uses - they were killing our build cycle and we need to stop giving them out so easily, although I don't know what standard we should use.

**Comment by kevee** [comment]
Like for example impaction, redirects should only be for like print ads or stuff like that, there is no reason to make one for emails and such.

**Comment by thburns** [comment]
Looks like https://csumb.edu/jobs got deleted. It is in our footer.

**Comment by kevee** [comment]
We can fix that.

**Comment by kevee** [comment]
OK I deleted way too many, restoring from yesterday's backup and I'll figure out a way to just handle this.

**Comment by kevee** [comment]
Reimported https://github.com/csumb/web-content/commit/96b0d01c230582a9749ae6acf0b6742866f97eb4
