### ISSUE TITLE
Bring back Finance Internal Site

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#233]
https://csumb.edu/internal/financetraining/

Just make it public at /financetraining/ like before

**Comment by thburns** [comment]
Any timeline for this one they are asking because its year end time and people are looking at this site @kevee

**Comment by kevee** [comment]
@thburns Done, I had to manually recreate their site, it's now back to a regular site at /financetraining

ref https://github.com/csumb/web-content/commit/ff135de4be4c28bcbe721da17bbd67db3453c475

**Comment by thburns** [comment]
@kevee can we scrub the website for anytime the internal is referenced? - for example https://csumb.edu/internal/internal/financetraining/end-fiscal-year-university is on https://csumb.edu/finance/accounting

If I get a list I can manually fix. If I knew you were going to manually fix it I would have just done that myself too.
