### ISSUE TITLE
More Broken links - Academic Senate

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#235]
https://edit.csumb.edu/senate/educational-planning-policy-committee-eppc vs https://csumb.edu/senate/educational-planning-policy-committee-eppc

This one - https://csumb.edu/senate/general-education-mist/curriculum-committee-ge-ge

This one - https://csumb.edu/senate/senate-mist/curriculum-committee-council-sccc

This one - https://csumb.edu/senate/university-requirement-mist/curriculum-committee-urcc-ad-hoc

**Comment by kevee** [comment]
Republished https://github.com/csumb/web-content/commit/c2ddeeaff1d77c8cbbe69871bd13ff6235e2970c

**Comment by kevee** [comment]
#239 - closing
