### ISSUE TITLE
Page feedback being collected anymore?

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#238]
hasn't been updated since the update - https://edit.csumb.edu/csumb/admin/feedback

**Comment by kevee** [comment]
Yes, feedback just gets emailed blindly and not stored anywhere... want me to have it CC webservices? @thburns

**Comment by thburns** [comment]
Yeah lets CC Webservices so we can check up on it from time to time.

**Comment by kevee** [comment]
https://github.com/csumb/data-api/commit/a23ad480a1354480fc0e378fd0e5dcbd691e5b42

**Comment by kevee** [comment]
Done.

**Comment by thburns** [comment]
It worked!
