### ISSUE TITLE
Broken link from an event

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#252]
https://csumb.edu/undocumentedstudents/events/end-year-celebration vs https://edit.csumb.edu/undocumentedstudents/events/end-year-celebration

can be found on https://csumb.edu/undocumentedstudents

**Comment by kevee** [comment]
Looks live.

**Comment by thburns** [comment]
The event images aren't the same now??? @kevee

**Comment by kevee** [comment]
The images look the same...

*Notice: *I am currently working remotely from Argentina, which is off
Pacific Time by 4 hours.

 Kevin Miller (he/him) 🏄
  Web Developer
  Cal State Monterey Bay - csumb.edu
  kevin@csumb.edu <kemiller@csumb.edu>

**Comment by thburns** [comment]
<img width="1232" alt="Screen Shot 2019-05-14 at 3 37 59 PM" src="https://user-images.githubusercontent.com/45435452/57736832-4e0d2b00-765e-11e9-8df6-a529ba107140.png">
<img width="1300" alt="Screen Shot 2019-05-14 at 3 38 07 PM" src="https://user-images.githubusercontent.com/45435452/57736833-4e0d2b00-765e-11e9-90e1-e87627006ddb.png">
