### ISSUE TITLE
TLA Broken Links They ave a meeting at Noon today

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#254]
https://edit.csumb.edu/tla/syllabus-guidelines vs https://csumb.edu/tla/syllabus-guidelines

https://csumb.edu/tla/transfer-reading-apprenticeship-csumb

https://csumb.edu/tla/teaching-cooperatives-201516-co-ops

**Comment by kevee** [comment]
Republishing site.

**Comment by kevee** [comment]
@thburns The first link was published, but the other two don't exist...
