### ISSUE TITLE
Bad link in Nav

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#285]
https://edit.csumb.edu/readingcenter/irene-moulton-administrative-services-coordinator vs https://csumb.edu/readingcenter/irene-moulton-administrative-services-coordinator was in the github list.

https://github.com/csumb/web-content/tree/master/readingcenter 

But it looks like https://csumb.edu/readingcenter/irene-moulton-administrative-support-coordinator exists.

**Comment by kevee** [comment]
Fixed https://github.com/csumb/web-content/commit/61c7b5326027f1cb1d6dcea1cd7fe0a9319aa053
