### ISSUE TITLE
nav links

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#288]
Looks like it is getting confused seld vs sald. It is now SELD.
seld | Archives | https://csumb.edu/sald/archives | 404 |   | https://edit.csumb.edu/seld |  

https://csumb.edu/schoolpsychology vs https://csumb.edu/SchoolPsychology

https://csumb.edu/hcom/english-subject-matter-prep-requirements this one seems a bit more complicated since it is an embedded page

**Comment by kevee** [comment]
https://github.com/csumb/web-content/commit/788b0c5ff2838dc405f01bd8a5bfb94543f8edd5

**Comment by kevee** [comment]
https://csumb.edu/SchoolPsychology is not a page, it's case sensitive.

**Comment by kevee** [comment]
The seld one was weird because it was a site name change. Fixed.
