### ISSUE TITLE
Page not working embeded or custom java script?

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#311]
https://csumb.edu/international/housing-options vs https://edit.csumb.edu/international/housing-options

Or its this page stopped working? - https://edit.csumb.edu/housing/compare-housing-options

**Comment by kevee** [comment]
@thburns The problem is this page: https://edit.csumb.edu/housing/compare-housing-options 

It's some crazy javascript page that references a now-unpublished Google spreadhseet.

**Comment by thburns** [comment]
Can you tell me what spreadsheet it is so i can follow up with James?
