### ISSUE TITLE
Events being wonky again images not matching up with events in feed

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#496]
https://csumb.edu/osu/virtual-programming

![events wonky](https://user-images.githubusercontent.com/45435452/91905281-2713a780-ec5b-11ea-8afa-2f70cf9fa9be.png)

**Comment by thburns** [comment]
When thinking about this the only thing that looks like might be messing it up is because they are on the same day?

**Comment by codywall** [comment]
Looks like this is still an issue.

**Comment by thburns** [comment]
Looks like its still an issue - https://csumb.edu/osu/virtual-programming

**Comment by codywall** [comment]
Okay, I think I finally found a solution for this. I had to level up my debugging skills, and it looked like the event feed was rendering twice. So I made sure to only render it once, when the events have been sorted. Hopefully we don't have this issue anymore.
