### ISSUE TITLE
AS navigation public docs arrow is out of place on iphone

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#506]
see image

![as nav](https://user-images.githubusercontent.com/45435452/92976844-5fc43580-f440-11ea-8bb1-cb933018ec7c.jpeg)

**Comment by thburns** [comment]
Still out of place on my iphone using safari

**Comment by codywall** [comment]
Just made another change and it looks good on my phone now. Looks good on yours @thburns ?
