### ISSUE TITLE
Table on mobile is overflowing the viewport

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#507]
https://csumb.edu/as/meetings

The table on mobile goes outside of the boundaries on mobile. at least iphone.

**Comment by codywall** [comment]
@flontoc, @thburns, what do you guys suggest we do about this? If I make the table headers small enough to fit on the page they will be unreadable and not accessible. Any ideas for how we should handle tables on mobile sitewide? The best option to me seems to be how the [Compare Housing]( https://csumb.edu/housing/compare-housing-options/) page handles it.

I could also make it so the table itself is swipeable/scrollable on mobile (#2 in this [article](https://medium.com/appnroll-publication/5-practical-solutions-to-make-responsive-data-tables-ff031c48b122).)
