### ISSUE TITLE
Swiftype (search) not updating with new info

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#509]
So my guess is this is the issue?

![Screen Shot 2020-09-15 at 3 43 48 PM](https://user-images.githubusercontent.com/45435452/93272530-8a78fb80-f76a-11ea-9aad-88ea2d3f6214.png)

 

I was trying to update this page as the title in the search engine isn't helpful right now.

![Screen Shot 2020-09-15 at 3 44 32 PM](https://user-images.githubusercontent.com/45435452/93272535-8e0c8280-f76a-11ea-8085-be11bcd04f05.png)

This is what Swiftype told us.

Sure thing! One thing that immediately stands out is that it appears that the is_site field was originally created with a data-type of integer but is now defined as a data-type of string within the meta tags on the page source. Once a field’s data-type is set, it is fixed. [1] What’s occurring now is that the document records are locked from being updated while the errant mapping type is being found in the pages.

If you’d like to have a field like is_site with a string data-type, you’ll need to either create a new engine, or re-name that field name value in the meta-tag so that a new field can be created. (ex. is_site-string)

Once that is resolved, you could also revisit the strategy for the data-inclusion/exclusion tagging. I do already see a true inclusion statement tag focused on the salient body content of pages. The most efficient way to invoke those tags are to mark the core content as true and then exclude any child elements within that container as false that you want to be excluded. Any false exclusion tags outside of that true containing element are extraneous and could be more cumbersome to manage. [2]

Then in terms of crawling your content, I can’t overstate the importance and benefit of using Sitemaps in addition to restricting crawling to a sitemap(s). We’ve a helpful guide here: https://swiftype.com/documentation/site-search/guides/crawler-optimization

Cleaning up the data being indexed, and reviewing the configuration of weights is a great place to start. Let us know of any outlier terms and we can take a closer look.

[1] https://swiftype.com/documentation/site-search/crawler-configuration/meta-tags#meta
[2] https://swiftype.com/documentation/site-search/crawler-configuration/content-inclusion-exclusion#nested

Access Your Case: https://support.elastic.co/customers/s/case/5004M00000eiW54

**Comment by codywall** [comment]
Tom, I looked into this, and it looks like it was just a mistake that this was defined as a string data type. Since the content of this tag is either 1 (true) or 0 (false), the integer data-type makes much more sense. I fixed it, and I don't think this is going to mess anything up. Once the site finishes building, go ahead and try what you were trying again and let me know what happens.
